### ISSUE TITLE
Strange files in repo

### ISSUE THREAD

**Issue by grzanka** [kevvw/ZADANIE3.1#2]
I see in the repo files without proper extensions: glowny and zaprzeczony_glowny.
What is their purpose ?

**Comment by pietrzykkevin** [comment]
I'm sorry for the misunderstanding the "glowny" file" ment to be zad3.1.c and "zaprzeczony_glowny" was ment to be nzad3.1.c thank you for your message, I have already fixed the problem, hope it because a bit clearer now.

**Comment by grzanka** [comment]
Great, you can close this issue
